apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: multi-httpd
          image: httpd
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
