---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  annotations:
    zarf.dev/connect-description: "Enter httpd!!!"
    zarf.dev/connect-url: "?httpd"
  labels:
    # Enables "zarf connect httpd"
    zarf.dev/connect-name: httpd
spec:
  selector:
    app: httpd
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  annotations:
    zarf.dev/connect-description: "Go to httpd website"
  labels:
    # Enables "zarf connect httpds"
    zarf.dev/connect-name: httpd
spec:
  selector:
    app: httpd
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
