trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildZarfPackage
    displayName: Build Zarf Package
    steps:
    - checkout: self

    - script: |
        echo "Installing Brew and Zarf CLI..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bash_profile
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.zshrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        source ~/.profile  # Or the appropriate file for your shell
        brew tap defenseunicorns/tap && brew install zarf
        az login --service-principal -u $(ServicePrincipalId) -p $(ServicePrincipalKey) --tenant $(TenantId)
        echo "Building Zarf package..."
        zarf package create ./zarf-package-yaml --confirm
        az aks get-credentials --resource-group test-k8s-resources --name example-aks1
        zarf init package --confirm
      displayName: 'Install Zarf CLI and Create Zarf Package'

    # Upload Zarf Package to Azure Blob Storage
    - script: |
        
        echo "Uploading Zarf package to Azure Blob Storage..."
        az storage blob upload --account-name rjzarfstorage --container-name zarf --file zarf-package-httpd-amd64-1.0.0.tar.zst --name zarf-package-httpd-amd64-1.0.0.tar.zst --sas-token "$(SasToken)" --overwrite
      displayName: 'Upload Zarf Package to Blob Storage'